export const GENDER_OPTIONS = ["Male", "Female", "Other"] as const;

export const PREFERRED_CITIES = [
  "Kathmandu",
  "Lalitpur",
  "Bhaktapur",
  "Other",
] as const;

/** Preferred Working Area — Kathmandu areas for join form. */
export const PREFERRED_WORKING_AREAS = [
  "Asan",
  "Balaju",
  "Baluwatar",
  "Baneshwor",
  "Basundhara",
  "Bhaisepati",
  "Bhaktapur",
  "Bouddha",
  "Budhanilkantha",
  "Chabahil",
  "Changunarayan",
  "Chundevi",
  "Dhapasi",
  "Durbar Marg",
  "Ekantakuna",
  "Gaushala",
  "Godawari",
  "Gongabu",
  "Gwarko",
  "Gyaneshwor",
  "Harisiddhi",
  "Imadol",
  "Jawalakhel",
  "Jorpati",
  "Kalanki",
  "Kalimati",
  "Kamalbinayak",
  "Kamalpokhari",
  "Kirtipur",
  "Koteshwor",
  "Khusibu",
  "Kupondole",
  "Lagankhel",
  "Lazimpat",
  "Machhapokhari",
  "Maharajgunj",
  "Mangal Bazar",
  "Naikap",
  "Nayabazar",
  "New Baneshwor",
  "New Road",
  "Patan",
  "Pulchowk",
  "Putalisadak",
  "Ranibari",
  "Samakhusi",
  "Sanepa",
  "Satdobato",
  "Sitapaila",
  "Sinamangal",
  "Sukedhara",
  "Sundhara",
  "Suryabinayak",
  "Swayambhu",
  "Teku",
  "Thamel",
  "Thaiba",
  "Thankot",
  "Thimi",
  "Tokha",
  "Tripureshwor",
  "Other",
] as const;

export const YEARS_OF_EXPERIENCE_OPTIONS = [
  "Less than 1 year",
  "1 year",
  "2 years",
  "3 years",
  "4 years",
  "5 years",
  "6–10 years",
  "11–15 years",
  "16–20 years",
  "More than 20 years",
] as const;

export const MAX_CAREER_FILE_MB = 5;
