-- Seed Kathmandu valley areas (single public.areas table — no cities table)
-- Safe to re-run (on conflict do nothing).

begin;


-- Kathmandu valley areas
insert into public.areas (name) values ('Kalanki') on conflict (name) do nothing;
insert into public.areas (name) values ('Kuleshwor') on conflict (name) do nothing;
insert into public.areas (name) values ('Kuleshwor Heights') on conflict (name) do nothing;
insert into public.areas (name) values ('Kalimati') on conflict (name) do nothing;
insert into public.areas (name) values ('Tripureshwor') on conflict (name) do nothing;
insert into public.areas (name) values ('Teku') on conflict (name) do nothing;
insert into public.areas (name) values ('Thapathali') on conflict (name) do nothing;
insert into public.areas (name) values ('Putalisadak') on conflict (name) do nothing;
insert into public.areas (name) values ('Putalisadak Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Bagbazar') on conflict (name) do nothing;
insert into public.areas (name) values ('Ratna Park') on conflict (name) do nothing;
insert into public.areas (name) values ('New Road') on conflict (name) do nothing;
insert into public.areas (name) values ('Indra Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Indrachowk Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Asan') on conflict (name) do nothing;
insert into public.areas (name) values ('Ason Tole') on conflict (name) do nothing;
insert into public.areas (name) values ('Jamal') on conflict (name) do nothing;
insert into public.areas (name) values ('Kamaladi') on conflict (name) do nothing;
insert into public.areas (name) values ('Durbar Marg') on conflict (name) do nothing;
insert into public.areas (name) values ('Durbar Square Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Lazimpat') on conflict (name) do nothing;
insert into public.areas (name) values ('Lazimpat Heights') on conflict (name) do nothing;
insert into public.areas (name) values ('Maharajgunj') on conflict (name) do nothing;
insert into public.areas (name) values ('Maharajgunj Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Baluwatar') on conflict (name) do nothing;
insert into public.areas (name) values ('Naxal') on conflict (name) do nothing;
insert into public.areas (name) values ('Naxal Bhagwati') on conflict (name) do nothing;
insert into public.areas (name) values ('Maitighar') on conflict (name) do nothing;
insert into public.areas (name) values ('Maitidevi') on conflict (name) do nothing;
insert into public.areas (name) values ('Baneshwor') on conflict (name) do nothing;
insert into public.areas (name) values ('New Baneshwor') on conflict (name) do nothing;
insert into public.areas (name) values ('Old Baneshwor') on conflict (name) do nothing;
insert into public.areas (name) values ('Purano Baneshwor') on conflict (name) do nothing;
insert into public.areas (name) values ('Mid-Baneshwor') on conflict (name) do nothing;
insert into public.areas (name) values ('Sinamangal') on conflict (name) do nothing;
insert into public.areas (name) values ('Gaushala') on conflict (name) do nothing;
insert into public.areas (name) values ('Chabahil') on conflict (name) do nothing;
insert into public.areas (name) values ('Ganesh Chowk Chabahil') on conflict (name) do nothing;
insert into public.areas (name) values ('Boudha') on conflict (name) do nothing;
insert into public.areas (name) values ('Boudha Jhyalungtar Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Jorpati') on conflict (name) do nothing;
insert into public.areas (name) values ('Gokarna') on conflict (name) do nothing;
insert into public.areas (name) values ('Gokarneshwor') on conflict (name) do nothing;
insert into public.areas (name) values ('Koteshwor') on conflict (name) do nothing;
insert into public.areas (name) values ('Tinkune') on conflict (name) do nothing;
insert into public.areas (name) values ('Pepsicola') on conflict (name) do nothing;
insert into public.areas (name) values ('Jadibuti') on conflict (name) do nothing;
insert into public.areas (name) values ('Anamnagar') on conflict (name) do nothing;
insert into public.areas (name) values ('Dillibazar') on conflict (name) do nothing;
insert into public.areas (name) values ('Gyaneshwor') on conflict (name) do nothing;
insert into public.areas (name) values ('Gyaneshwor Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Battisputali') on conflict (name) do nothing;
insert into public.areas (name) values ('Samakhusi') on conflict (name) do nothing;
insert into public.areas (name) values ('Samakhusi Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Gongabu') on conflict (name) do nothing;
insert into public.areas (name) values ('Gongabu Bus Park Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Tokha Road') on conflict (name) do nothing;
insert into public.areas (name) values ('Tokha') on conflict (name) do nothing;
insert into public.areas (name) values ('Tokha Bazaar') on conflict (name) do nothing;
insert into public.areas (name) values ('Basundhara') on conflict (name) do nothing;
insert into public.areas (name) values ('Basundhara Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Balaju') on conflict (name) do nothing;
insert into public.areas (name) values ('Balaju Bypass Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Swayambhu') on conflict (name) do nothing;
insert into public.areas (name) values ('Sitapaila') on conflict (name) do nothing;
insert into public.areas (name) values ('Nayabazar') on conflict (name) do nothing;
insert into public.areas (name) values ('Sorhakhutte') on conflict (name) do nothing;
insert into public.areas (name) values ('Thamel') on conflict (name) do nothing;
insert into public.areas (name) values ('Paknajol') on conflict (name) do nothing;
insert into public.areas (name) values ('Chhetrapati') on conflict (name) do nothing;
insert into public.areas (name) values ('Dallu') on conflict (name) do nothing;
insert into public.areas (name) values ('Kirtipur') on conflict (name) do nothing;
insert into public.areas (name) values ('Kirtipur Bazaar') on conflict (name) do nothing;
insert into public.areas (name) values ('Panga') on conflict (name) do nothing;
insert into public.areas (name) values ('Tyanglaphat') on conflict (name) do nothing;
insert into public.areas (name) values ('Chovar') on conflict (name) do nothing;
insert into public.areas (name) values ('Balkhu') on conflict (name) do nothing;
insert into public.areas (name) values ('TU Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Thankot') on conflict (name) do nothing;
insert into public.areas (name) values ('Budhanilkantha') on conflict (name) do nothing;
insert into public.areas (name) values ('Ranibari') on conflict (name) do nothing;
insert into public.areas (name) values ('Rani Bari') on conflict (name) do nothing;
insert into public.areas (name) values ('Banasthali') on conflict (name) do nothing;
insert into public.areas (name) values ('Banasthali Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Kapan') on conflict (name) do nothing;
insert into public.areas (name) values ('Kapan Heights') on conflict (name) do nothing;
insert into public.areas (name) values ('Mandikhatar') on conflict (name) do nothing;
insert into public.areas (name) values ('Hattigauda') on conflict (name) do nothing;
insert into public.areas (name) values ('Golfutar') on conflict (name) do nothing;
insert into public.areas (name) values ('Narayan Gopal Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Sukedhara') on conflict (name) do nothing;
insert into public.areas (name) values ('Dhapasi') on conflict (name) do nothing;
insert into public.areas (name) values ('Dhapasi Height') on conflict (name) do nothing;
insert into public.areas (name) values ('Manamaiju') on conflict (name) do nothing;
insert into public.areas (name) values ('Ichangu Narayan') on conflict (name) do nothing;
insert into public.areas (name) values ('Ramkot') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhimdhunga') on conflict (name) do nothing;
insert into public.areas (name) values ('Goldhunga') on conflict (name) do nothing;
insert into public.areas (name) values ('Mhepi') on conflict (name) do nothing;
insert into public.areas (name) values ('Mhepi Height') on conflict (name) do nothing;
insert into public.areas (name) values ('Tangal') on conflict (name) do nothing;
insert into public.areas (name) values ('Bishalnagar') on conflict (name) do nothing;
insert into public.areas (name) values ('Handigaon') on conflict (name) do nothing;
insert into public.areas (name) values ('Minbhawan') on conflict (name) do nothing;
insert into public.areas (name) values ('Shantinagar') on conflict (name) do nothing;
insert into public.areas (name) values ('Shantinagar Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Kumarigal') on conflict (name) do nothing;
insert into public.areas (name) values ('Sundhara') on conflict (name) do nothing;
insert into public.areas (name) values ('Sundhara Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Lainchaur') on conflict (name) do nothing;
insert into public.areas (name) values ('Lainchaur Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Maru') on conflict (name) do nothing;
insert into public.areas (name) values ('Kilagal') on conflict (name) do nothing;
insert into public.areas (name) values ('Ombahal') on conflict (name) do nothing;
insert into public.areas (name) values ('Jyatha') on conflict (name) do nothing;
insert into public.areas (name) values ('Nardevi') on conflict (name) do nothing;
insert into public.areas (name) values ('Makhan') on conflict (name) do nothing;
insert into public.areas (name) values ('Wotu') on conflict (name) do nothing;
insert into public.areas (name) values ('Bangemudha') on conflict (name) do nothing;
insert into public.areas (name) values ('Tahachal') on conflict (name) do nothing;
insert into public.areas (name) values ('Soltimode') on conflict (name) do nothing;
insert into public.areas (name) values ('Ravi Bhawan') on conflict (name) do nothing;
insert into public.areas (name) values ('Syuchatar') on conflict (name) do nothing;
insert into public.areas (name) values ('Nagarjun') on conflict (name) do nothing;
insert into public.areas (name) values ('Bafal') on conflict (name) do nothing;
insert into public.areas (name) values ('Sano Bharyang') on conflict (name) do nothing;
insert into public.areas (name) values ('Balambu') on conflict (name) do nothing;
insert into public.areas (name) values ('Chunikhel') on conflict (name) do nothing;
insert into public.areas (name) values ('Bansbari') on conflict (name) do nothing;
insert into public.areas (name) values ('Dhumbarahi') on conflict (name) do nothing;
insert into public.areas (name) values ('Akashedhara') on conflict (name) do nothing;
insert into public.areas (name) values ('Saraswatinagar') on conflict (name) do nothing;
insert into public.areas (name) values ('Kharibot') on conflict (name) do nothing;
insert into public.areas (name) values ('Kharibot Kapan') on conflict (name) do nothing;
insert into public.areas (name) values ('Om Hospital Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Mulpani') on conflict (name) do nothing;
insert into public.areas (name) values ('Mulpani Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Mulpani Heights') on conflict (name) do nothing;
insert into public.areas (name) values ('Mulpani Colony Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Gairidhara') on conflict (name) do nothing;
insert into public.areas (name) values ('Baluwakhani') on conflict (name) do nothing;
insert into public.areas (name) values ('Chapali') on conflict (name) do nothing;
insert into public.areas (name) values ('Chapali Ghumti') on conflict (name) do nothing;
insert into public.areas (name) values ('Khadka Gaun') on conflict (name) do nothing;
insert into public.areas (name) values ('Tusal') on conflict (name) do nothing;
insert into public.areas (name) values ('Tusal Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Tusal Boudha Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Pipalbot') on conflict (name) do nothing;
insert into public.areas (name) values ('Mahankal') on conflict (name) do nothing;
insert into public.areas (name) values ('Ramhiti') on conflict (name) do nothing;
insert into public.areas (name) values ('Narayantar') on conflict (name) do nothing;
insert into public.areas (name) values ('Baluwa Khani') on conflict (name) do nothing;
insert into public.areas (name) values ('Khadka Bhadrakali') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhatbhateni') on conflict (name) do nothing;
insert into public.areas (name) values ('Milan Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Milan Chowk Kapan') on conflict (name) do nothing;
insert into public.areas (name) values ('Kapurdhara') on conflict (name) do nothing;
insert into public.areas (name) values ('Teaching Hospital Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Chundevi') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhangal') on conflict (name) do nothing;
insert into public.areas (name) values ('Dhokan') on conflict (name) do nothing;
insert into public.areas (name) values ('Pasikot') on conflict (name) do nothing;
insert into public.areas (name) values ('Bishnudwar') on conflict (name) do nothing;
insert into public.areas (name) values ('Bodhigram Road Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Jagdol') on conflict (name) do nothing;
insert into public.areas (name) values ('Guhyeshwari') on conflict (name) do nothing;
insert into public.areas (name) values ('Pashupati Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Tilganga') on conflict (name) do nothing;
insert into public.areas (name) values ('Airport Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Civil Homes Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Manohara Corridor') on conflict (name) do nothing;
insert into public.areas (name) values ('Manohara') on conflict (name) do nothing;
insert into public.areas (name) values ('Harisiddhi Border Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Machhegaun') on conflict (name) do nothing;
insert into public.areas (name) values ('Bosan') on conflict (name) do nothing;
insert into public.areas (name) values ('Dhaksi') on conflict (name) do nothing;
insert into public.areas (name) values ('Futung') on conflict (name) do nothing;
insert into public.areas (name) values ('Jitpurphedi') on conflict (name) do nothing;
insert into public.areas (name) values ('Grande Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Greenland') on conflict (name) do nothing;
insert into public.areas (name) values ('Besarigaun') on conflict (name) do nothing;
insert into public.areas (name) values ('Sankhu') on conflict (name) do nothing;
insert into public.areas (name) values ('Bajrayogini') on conflict (name) do nothing;
insert into public.areas (name) values ('Salinadi') on conflict (name) do nothing;
insert into public.areas (name) values ('Suntol') on conflict (name) do nothing;
insert into public.areas (name) values ('Narephat') on conflict (name) do nothing;
insert into public.areas (name) values ('Kageshwori') on conflict (name) do nothing;
insert into public.areas (name) values ('Danchi') on conflict (name) do nothing;
insert into public.areas (name) values ('Aalapot') on conflict (name) do nothing;
insert into public.areas (name) values ('Thali') on conflict (name) do nothing;
insert into public.areas (name) values ('Bode Border Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Kamalbinayak Border Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Gatthaghar Border Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Dhobighat Border Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Khusibu') on conflict (name) do nothing;
insert into public.areas (name) values ('Lekhnath Marg Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhimsengola') on conflict (name) do nothing;
insert into public.areas (name) values ('Aloknagar') on conflict (name) do nothing;
insert into public.areas (name) values ('Devkota Sadak Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Devkota Sadak') on conflict (name) do nothing;
insert into public.areas (name) values ('Shovabhagwati') on conflict (name) do nothing;
insert into public.areas (name) values ('Dhalko') on conflict (name) do nothing;
insert into public.areas (name) values ('Kankeshwari') on conflict (name) do nothing;
insert into public.areas (name) values ('Ganeshthan') on conflict (name) do nothing;
insert into public.areas (name) values ('Pingalasthan') on conflict (name) do nothing;
insert into public.areas (name) values ('Old Bus Park Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Old Bus Park') on conflict (name) do nothing;
insert into public.areas (name) values ('Kantipath Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Kantipath') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhadrakali') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhadrakali Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Rani Pokhari') on conflict (name) do nothing;
insert into public.areas (name) values ('Rani Pokhari Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Hattisar') on conflict (name) do nothing;
insert into public.areas (name) values ('Kamal Pokhari') on conflict (name) do nothing;
insert into public.areas (name) values ('Babarmahal') on conflict (name) do nothing;
insert into public.areas (name) values ('Bijulibazar') on conflict (name) do nothing;
insert into public.areas (name) values ('Shankhamul') on conflict (name) do nothing;
insert into public.areas (name) values ('UN Park Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Sifal') on conflict (name) do nothing;
insert into public.areas (name) values ('Gaurighat') on conflict (name) do nothing;
insert into public.areas (name) values ('Mitrapark') on conflict (name) do nothing;
insert into public.areas (name) values ('Setopul') on conflict (name) do nothing;
insert into public.areas (name) values ('Sano Gaucharan') on conflict (name) do nothing;
insert into public.areas (name) values ('Brikutimandap') on conflict (name) do nothing;
insert into public.areas (name) values ('Exhibition Road') on conflict (name) do nothing;
insert into public.areas (name) values ('Dharahara Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Nagpokhari') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhagwan Bahal') on conflict (name) do nothing;
insert into public.areas (name) values ('Thahity') on conflict (name) do nothing;
insert into public.areas (name) values ('Jhochhen') on conflict (name) do nothing;
insert into public.areas (name) values ('Freak Street') on conflict (name) do nothing;
insert into public.areas (name) values ('Kel Tole') on conflict (name) do nothing;
insert into public.areas (name) values ('Hyumat') on conflict (name) do nothing;
insert into public.areas (name) values ('Lagan Tole') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhimsensthan') on conflict (name) do nothing;
insert into public.areas (name) values ('Tebahal') on conflict (name) do nothing;
insert into public.areas (name) values ('Itum Bahal') on conflict (name) do nothing;
insert into public.areas (name) values ('Mahabouddha') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhotahity') on conflict (name) do nothing;
insert into public.areas (name) values ('Nhyokha') on conflict (name) do nothing;
insert into public.areas (name) values ('Pyafal') on conflict (name) do nothing;
insert into public.areas (name) values ('Tankeshwor') on conflict (name) do nothing;
insert into public.areas (name) values ('Makanpur') on conflict (name) do nothing;
insert into public.areas (name) values ('Naikap') on conflict (name) do nothing;
insert into public.areas (name) values ('Satungal') on conflict (name) do nothing;
insert into public.areas (name) values ('Matatirtha') on conflict (name) do nothing;
insert into public.areas (name) values ('Dahachok') on conflict (name) do nothing;
insert into public.areas (name) values ('Kavresthali') on conflict (name) do nothing;
insert into public.areas (name) values ('Machhapokhari') on conflict (name) do nothing;
insert into public.areas (name) values ('New Bus Park Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Balmandir Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Narayanhiti Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Singha Durbar Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Bagdurbar Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Arubari') on conflict (name) do nothing;

-- More valley areas
insert into public.areas (name) values ('Bhaktapur Durbar Square') on conflict (name) do nothing;
insert into public.areas (name) values ('Suryabinayak') on conflict (name) do nothing;
insert into public.areas (name) values ('Suryabinayak Heights') on conflict (name) do nothing;
insert into public.areas (name) values ('Suryabinayak Temple Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Thimi') on conflict (name) do nothing;
insert into public.areas (name) values ('Madhyapur Thimi') on conflict (name) do nothing;
insert into public.areas (name) values ('Naya Thimi') on conflict (name) do nothing;
insert into public.areas (name) values ('Sanothimi') on conflict (name) do nothing;
insert into public.areas (name) values ('Bode') on conflict (name) do nothing;
insert into public.areas (name) values ('Bode New Settlement Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Nagadesh') on conflict (name) do nothing;
insert into public.areas (name) values ('Balkot') on conflict (name) do nothing;
insert into public.areas (name) values ('Balkot Heights') on conflict (name) do nothing;
insert into public.areas (name) values ('Gatthaghar') on conflict (name) do nothing;
insert into public.areas (name) values ('Kaushaltar') on conflict (name) do nothing;
insert into public.areas (name) values ('Kaushaltar Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Lokanthali') on conflict (name) do nothing;
insert into public.areas (name) values ('Duwakot') on conflict (name) do nothing;
insert into public.areas (name) values ('Duwakot Industrial Corridor') on conflict (name) do nothing;
insert into public.areas (name) values ('Sirutar') on conflict (name) do nothing;
insert into public.areas (name) values ('Jagati') on conflict (name) do nothing;
insert into public.areas (name) values ('Sallaghari') on conflict (name) do nothing;
insert into public.areas (name) values ('Sallaghari Forest Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Chyamasingh') on conflict (name) do nothing;
insert into public.areas (name) values ('Chyamhasingh') on conflict (name) do nothing;
insert into public.areas (name) values ('Byasi') on conflict (name) do nothing;
insert into public.areas (name) values ('Byasi Heritage Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Golmadhi') on conflict (name) do nothing;
insert into public.areas (name) values ('Golmadhi Pottery Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Taumadhi') on conflict (name) do nothing;
insert into public.areas (name) values ('Taumadhi Heritage Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Taumadhi Square') on conflict (name) do nothing;
insert into public.areas (name) values ('Kamalbinayak') on conflict (name) do nothing;
insert into public.areas (name) values ('Kamalbinayak Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Barahisthan') on conflict (name) do nothing;
insert into public.areas (name) values ('Barahisthan Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Sipadol') on conflict (name) do nothing;
insert into public.areas (name) values ('Nangkhel') on conflict (name) do nothing;
insert into public.areas (name) values ('Sudal') on conflict (name) do nothing;
insert into public.areas (name) values ('Tathali') on conflict (name) do nothing;
insert into public.areas (name) values ('Gundu') on conflict (name) do nothing;
insert into public.areas (name) values ('Dadhikot') on conflict (name) do nothing;
insert into public.areas (name) values ('Katunje') on conflict (name) do nothing;
insert into public.areas (name) values ('Chittapol') on conflict (name) do nothing;
insert into public.areas (name) values ('Changunarayan') on conflict (name) do nothing;
insert into public.areas (name) values ('Changunarayan Hill Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Jhaukhel') on conflict (name) do nothing;
insert into public.areas (name) values ('Kharipati') on conflict (name) do nothing;
insert into public.areas (name) values ('Kharipati Military Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Manohara') on conflict (name) do nothing;
insert into public.areas (name) values ('Manohara Riverside Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Dibyashwori') on conflict (name) do nothing;
insert into public.areas (name) values ('Liwali') on conflict (name) do nothing;
insert into public.areas (name) values ('Liwali Ground Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Palanse') on conflict (name) do nothing;
insert into public.areas (name) values ('Inacho') on conflict (name) do nothing;
insert into public.areas (name) values ('Sukuldhoka') on conflict (name) do nothing;
insert into public.areas (name) values ('Sukuldhoka Heritage Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Dudhpati') on conflict (name) do nothing;
insert into public.areas (name) values ('Hanumanghat') on conflict (name) do nothing;
insert into public.areas (name) values ('Hanumante Corridor') on conflict (name) do nothing;
insert into public.areas (name) values ('Bekhal') on conflict (name) do nothing;
insert into public.areas (name) values ('Chhaling') on conflict (name) do nothing;
insert into public.areas (name) values ('Telkot') on conflict (name) do nothing;
insert into public.areas (name) values ('Telkot Hill Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Nalinchowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Nalinchowk Industrial Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Bageshwori') on conflict (name) do nothing;
insert into public.areas (name) values ('Bageshwori Corridor') on conflict (name) do nothing;
insert into public.areas (name) values ('Maheshwori') on conflict (name) do nothing;
insert into public.areas (name) values ('Dekocha') on conflict (name) do nothing;
insert into public.areas (name) values ('Dekocha Industrial Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Itapakha') on conflict (name) do nothing;
insert into public.areas (name) values ('Khauma') on conflict (name) do nothing;
insert into public.areas (name) values ('Tachupal Tole') on conflict (name) do nothing;
insert into public.areas (name) values ('Tachupal Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Pottery Square') on conflict (name) do nothing;
insert into public.areas (name) values ('Pottery Square Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Radhe Radhe') on conflict (name) do nothing;
insert into public.areas (name) values ('Radhe Radhe Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Pilachhen') on conflict (name) do nothing;
insert into public.areas (name) values ('Mibachhen') on conflict (name) do nothing;
insert into public.areas (name) values ('Talako Tole') on conflict (name) do nothing;
insert into public.areas (name) values ('Yachhen') on conflict (name) do nothing;
insert into public.areas (name) values ('Kwathandau') on conflict (name) do nothing;
insert into public.areas (name) values ('Chupinghat') on conflict (name) do nothing;
insert into public.areas (name) values ('Ghyampedanda') on conflict (name) do nothing;
insert into public.areas (name) values ('Tiwari Tol') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhelukhel') on conflict (name) do nothing;
insert into public.areas (name) values ('Chwasa') on conflict (name) do nothing;
insert into public.areas (name) values ('Bolachhen') on conflict (name) do nothing;
insert into public.areas (name) values ('Wanla') on conflict (name) do nothing;
insert into public.areas (name) values ('Pikulachhen') on conflict (name) do nothing;
insert into public.areas (name) values ('Suryamadhi') on conflict (name) do nothing;
insert into public.areas (name) values ('Chochhen') on conflict (name) do nothing;
insert into public.areas (name) values ('Nayatola') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhulachhi') on conflict (name) do nothing;
insert into public.areas (name) values ('Khel Tole') on conflict (name) do nothing;
insert into public.areas (name) values ('Gahiti') on conflict (name) do nothing;
insert into public.areas (name) values ('Dattatreya Square') on conflict (name) do nothing;
insert into public.areas (name) values ('Dattatreya Heritage Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Nyatapola Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Wakupati Narayan') on conflict (name) do nothing;
insert into public.areas (name) values ('Bansagopal Tole') on conflict (name) do nothing;
insert into public.areas (name) values ('Navadurga Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Brahmayani Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Kamal Pokhari Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Ram Mandir Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Brindaban Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Chundevi Tole') on conflict (name) do nothing;
insert into public.areas (name) values ('Machedhunga Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Sanga') on conflict (name) do nothing;
insert into public.areas (name) values ('Palubari') on conflict (name) do nothing;
insert into public.areas (name) values ('Mandev') on conflict (name) do nothing;
insert into public.areas (name) values ('Pandubazar') on conflict (name) do nothing;
insert into public.areas (name) values ('Jagate') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhaktapur Bus Park Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Araniko Highway Corridor') on conflict (name) do nothing;
insert into public.areas (name) values ('Ganesh Temple Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Pilot Baba Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Ranikot') on conflict (name) do nothing;
insert into public.areas (name) values ('Ranikot Road Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Doleshwor Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Jalapadevi Area') on conflict (name) do nothing;

-- More valley areas
insert into public.areas (name) values ('Patan Durbar Square') on conflict (name) do nothing;
insert into public.areas (name) values ('Jawalakhel') on conflict (name) do nothing;
insert into public.areas (name) values ('Pulchowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Kupondole') on conflict (name) do nothing;
insert into public.areas (name) values ('Lagankhel') on conflict (name) do nothing;
insert into public.areas (name) values ('Lagankhel Bus Park Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Mangal Bazaar') on conflict (name) do nothing;
insert into public.areas (name) values ('Kumaripati') on conflict (name) do nothing;
insert into public.areas (name) values ('Kumaripati Heights') on conflict (name) do nothing;
insert into public.areas (name) values ('Sanepa') on conflict (name) do nothing;
insert into public.areas (name) values ('Satdobato') on conflict (name) do nothing;
insert into public.areas (name) values ('Imadol') on conflict (name) do nothing;
insert into public.areas (name) values ('Imadol Heights') on conflict (name) do nothing;
insert into public.areas (name) values ('Tikathali') on conflict (name) do nothing;
insert into public.areas (name) values ('Tikathali Heights') on conflict (name) do nothing;
insert into public.areas (name) values ('Tikathali Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Harisiddhi') on conflict (name) do nothing;
insert into public.areas (name) values ('Harisiddhi Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Godawari') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhaisepati') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhaisepati Heights') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhaisepati Corridor') on conflict (name) do nothing;
insert into public.areas (name) values ('Dhapakhel') on conflict (name) do nothing;
insert into public.areas (name) values ('Dhapakhel Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Nakhu') on conflict (name) do nothing;
insert into public.areas (name) values ('Nakkhu') on conflict (name) do nothing;
insert into public.areas (name) values ('Ekantakuna') on conflict (name) do nothing;
insert into public.areas (name) values ('Chapagaun') on conflict (name) do nothing;
insert into public.areas (name) values ('Chapagaun Dobato') on conflict (name) do nothing;
insert into public.areas (name) values ('Bungamati') on conflict (name) do nothing;
insert into public.areas (name) values ('Bungamati Heritage Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Bungamati New Road Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Khokana') on conflict (name) do nothing;
insert into public.areas (name) values ('Khokana Heritage Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Khokana New Town Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Sano Khokana') on conflict (name) do nothing;
insert into public.areas (name) values ('Lubhu') on conflict (name) do nothing;
insert into public.areas (name) values ('Lubhu Heights') on conflict (name) do nothing;
insert into public.areas (name) values ('Lamatar') on conflict (name) do nothing;
insert into public.areas (name) values ('Lamatar Heights') on conflict (name) do nothing;
insert into public.areas (name) values ('Sunakothi') on conflict (name) do nothing;
insert into public.areas (name) values ('Thecho') on conflict (name) do nothing;
insert into public.areas (name) values ('Thaiba') on conflict (name) do nothing;
insert into public.areas (name) values ('Chyasal') on conflict (name) do nothing;
insert into public.areas (name) values ('Gabahal') on conflict (name) do nothing;
insert into public.areas (name) values ('Patan Dhoka') on conflict (name) do nothing;
insert into public.areas (name) values ('Balkumari') on conflict (name) do nothing;
insert into public.areas (name) values ('Siddhipur') on conflict (name) do nothing;
insert into public.areas (name) values ('Lele') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhattedanda') on conflict (name) do nothing;
insert into public.areas (name) values ('Chaughare') on conflict (name) do nothing;
insert into public.areas (name) values ('Ashrang') on conflict (name) do nothing;
insert into public.areas (name) values ('Gotikhel') on conflict (name) do nothing;
insert into public.areas (name) values ('Bukhel') on conflict (name) do nothing;
insert into public.areas (name) values ('Malta') on conflict (name) do nothing;
insert into public.areas (name) values ('Dalchoki') on conflict (name) do nothing;
insert into public.areas (name) values ('Gimdi') on conflict (name) do nothing;
insert into public.areas (name) values ('Manikhel') on conflict (name) do nothing;
insert into public.areas (name) values ('Taukhel') on conflict (name) do nothing;
insert into public.areas (name) values ('Badikhel') on conflict (name) do nothing;
insert into public.areas (name) values ('Pyutar') on conflict (name) do nothing;
insert into public.areas (name) values ('Chhampi') on conflict (name) do nothing;
insert into public.areas (name) values ('Jharuwarasi') on conflict (name) do nothing;
insert into public.areas (name) values ('Sainbu') on conflict (name) do nothing;
insert into public.areas (name) values ('Sainbu Bhainsepati Road Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Khumaltar') on conflict (name) do nothing;
insert into public.areas (name) values ('Hattiban') on conflict (name) do nothing;
insert into public.areas (name) values ('Tika Bhairab') on conflict (name) do nothing;
insert into public.areas (name) values ('Tikabhairab Bazaar') on conflict (name) do nothing;
insert into public.areas (name) values ('Choighare') on conflict (name) do nothing;
insert into public.areas (name) values ('Machhegaun') on conflict (name) do nothing;
insert into public.areas (name) values ('Dholahiti') on conflict (name) do nothing;
insert into public.areas (name) values ('Kusunti') on conflict (name) do nothing;
insert into public.areas (name) values ('Dhobighat') on conflict (name) do nothing;
insert into public.areas (name) values ('Jhamsikhel') on conflict (name) do nothing;
insert into public.areas (name) values ('UN Park Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Mahalaxmisthan') on conflict (name) do nothing;
insert into public.areas (name) values ('Mahalaxmi Municipality Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Gwarko') on conflict (name) do nothing;
insert into public.areas (name) values ('Ochu Height') on conflict (name) do nothing;
insert into public.areas (name) values ('Kitini') on conflict (name) do nothing;
insert into public.areas (name) values ('Badegaun') on conflict (name) do nothing;
insert into public.areas (name) values ('Nallu') on conflict (name) do nothing;
insert into public.areas (name) values ('Bisankhunarayan') on conflict (name) do nothing;
insert into public.areas (name) values ('Phulchoki Base Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Chapakharka') on conflict (name) do nothing;
insert into public.areas (name) values ('Shankhu') on conflict (name) do nothing;
insert into public.areas (name) values ('Bhardeu') on conflict (name) do nothing;
insert into public.areas (name) values ('Devichaur') on conflict (name) do nothing;
insert into public.areas (name) values ('Baguwa') on conflict (name) do nothing;
insert into public.areas (name) values ('Ghusel') on conflict (name) do nothing;
insert into public.areas (name) values ('Makwanpur Border Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Lakuri Bhanjyang') on conflict (name) do nothing;
insert into public.areas (name) values ('Bajrabarahi') on conflict (name) do nothing;
insert into public.areas (name) values ('Karyabinayak') on conflict (name) do nothing;
insert into public.areas (name) values ('Suryodaya Colony') on conflict (name) do nothing;
insert into public.areas (name) values ('Goldhunga Lalitpur Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Kharibot Lalitpur Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Godamchaur') on conflict (name) do nothing;
insert into public.areas (name) values ('Chohar') on conflict (name) do nothing;
insert into public.areas (name) values ('Arubot') on conflict (name) do nothing;
insert into public.areas (name) values ('Madan Smarak Road Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Nakhipot') on conflict (name) do nothing;
insert into public.areas (name) values ('Nakhipot Chowk') on conflict (name) do nothing;
insert into public.areas (name) values ('Nayabasti') on conflict (name) do nothing;
insert into public.areas (name) values ('Balkot Border Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Sunrise Height Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Luvu Bus Park Area') on conflict (name) do nothing;
insert into public.areas (name) values ('Buddha Park Area') on conflict (name) do nothing;

commit;

-- Verify:
-- select count(*) from public.areas;
